tap "homebrew/bundle"
tap "homebrew/services"

brew "gcc"
brew "git"
brew "gradle"
brew "neovim"
brew "node"
brew "ripgrep"
brew "stow"
brew "starship"
brew "code-cli"
brew "dotnet"
brew "xclip"
brew "unzip"

cask "android-studio"
cask "font-jetbrains-mono-nerd-font"
cask "kitty"
cask "postman"
cask "spotify"
cask "visual-studio-code"
