tap "homebrew/bundle"
tap "homebrew/services"
tap "osx-cross/arm"
tap "osx-cross/avr"

brew "git"
brew "gradle"
brew "kotlin"
brew "neovim"
brew "node"
brew "ripgrep"
brew "stow"
brew "starship"
brew "osx-cross/arm/arm-gcc-bin@10"
brew "code-cli"
brew "dotnet"

cask "android-studio"
cask "font-jetbrains-mono-nerd-font"
cask "kitty"
cask "postman"
cask "spotify"
cask "visual-studio-code"
cask "xquartz"
